version: '3.8'
services:
  spmath-app:
    container_name: spmath-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - spmath-db
    networks:
      - laravel-net

  spmath-nginx:
    image: nginx:latest
    container_name: spmath-nginx
    restart: unless-stopped
    ports:
      - "8004:80" # Map host port 8000 to Nginx container port 80
      - "8446:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./nginx/ssl/:/etc/nginx/ssl/
    depends_on:
      - spmath-app
    networks:
      - laravel-net

  spmath-db:
    image: mysql:latest
    container_name: spmath-db
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3310:3309" # Map host port 3306 to MySQL container port 3306
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
